version: '3'

services:
  web1:
    image: hyena
    container_name: hyenaA
    depends_on:
      - redis
    environment:
      - PORT=5000
      - BID=A
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MASTER_HOST=ringmaster
      - MASTER_PORT=9091
    ports:
      - "5001:5000"
    networks:
      - nodenet

  web2:
    image: hyena
    container_name: hyenaB
    depends_on:
      - redis
    environment:
      - PORT=5000
      - BID=B
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MASTER_HOST=ringmaster
      - MASTER_PORT=9091      
    ports:
      - "5002:5000"
    networks:
      - nodenet

  web3:
    image: hyena
    container_name: hyenaC
    depends_on:
      - redis
    environment:
      - PORT=5000
      - BID=C
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MASTER_HOST=ringmaster
      - MASTER_PORT=9091      
    ports:
      - "5003:5000"
    networks:
      - nodenet

  web4:
    image: hyena
    container_name: hyenaD
    depends_on:
      - redis
    environment:
      - PORT=5000
      - BID=D
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MASTER_HOST=ringmaster
      - MASTER_PORT=9091      
    ports:
      - "5004:5000"
    networks:
      - nodenet

  ringmaster:
    image: ringmaster
    container_name: ringmaster
    environment:
      - PORT=9091    
    ports:
      - "9091:9091"
    networks:
      - nodenet

  redis:
    image: redis
    depends_on:
      - ringmaster
    container_name: redis_container
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge
